version: "3.9"

networks:
  landing:

services:
  nginx: 
    image: nginx:stable-alpine
    restart: always
    ports:
      - "1488:80"
    volumes:
        - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
    networks:
      - landing

  frontend: 
    build:
      context: ./landing
    restart: always
    networks:
      - landing